import { Surge } from './surge';

export const SURGES: Surge[] = [
  { id: 1, name: '1d6 flumphs controlled by the DM appear in unoccupied spaces within 60 ft of you and are frightened of you. They vanish after 1 minute.' },
  { id: 2, name: '3d6 x 100 gold rain down in a 20 ft radius.  Take 1d4 per 100 gold damage.' },
  { id: 3, name: '3d6 random gems appear near you, worth 50gp each.' },
  { id: 4, name: '3d6 silver pieces appear near you.' },
  { id: 5, name: 'A 30 ft cube hypnotic pattern appears with you at the center. All creatures within the pattern must succeed on a Wisdom saving throw or fall asleep for 1 minute or until they take damage.' },
  { id: 6, name: 'A bad joke comes to mind and until you tell it (which takes an entire action), you suffer a Wisdom penalty of 1.' },
  { id: 7, name: 'A confused bear appears within 60 ft for 1 minute' },
  { id: 8, name: 'A demon whose CR is equal to your level appears near you. Make a Charisma saving throw against your spell save DC. If you make it, the demon is subservient, otherwise, it is hostile. The demon, if not banished or defeated, vanishes after 1 day.' },
  { id: 9, name: 'A fireball explodes with you at the center. You and each creature within 20 ft of you who must make a Dexterity saving throw using your spell save DC, taking 5d6 fire damage on a failed save, or half as much damage on a successful one.' },
  { id: 10, name: 'A flaming horse appears (Not Nightmare, real horse)' },
  { id: 11, name: 'A gentle gust of wind blows outward from you. All creatures within 40 ft of you can feel it, but it otherwise does nothing.' },
  { id: 12, name: 'A ghoul under your control rises from the earth. It ceases to be controlled by you in 1d4 hours.' },
  { id: 13, name: 'A hell hound controlled by the DM appears within 5 ft of you, then disappears 1 minute later.' },
  { id: 14, name: 'A loud boom emanates from you. All creatures within 15 ft take 2d8 thunder damage and must make a Constitution saving throw against your spell save DC or be deafened for 1 minute.' },
  { id: 15, name: 'A magic mouth appears on a nearby wall or flat surface. When you speak, your voice comes from the magic mouth. This lasts for 1 minute.' },
  { id: 16, name: 'A mature oak sprouts in an unoccupied space in 60 ft' },
  { id: 17, name: 'A modron chosen and controlled by the DM appears in an unoccupied space within 5 ft of you, then disappears I minute later.' },
  { id: 18, name: 'A puddle of grease appears where you are standing, with a 10 ft radius. You and anyone within 10 ft of you must make a Dexterity check at your spell save DC or fall prone.' },
  { id: 19, name: 'A random creature within 30 ft of you gains a flying speed equal to its walking speed for 1 minute.' },
  { id: 20, name: 'A random creature within 60 ft of you becomes poisoned for 1d4 hours.' },
  { id: 21, name: 'A random creature within 60 ft of you is poisoned for 1d4 hours.' },
  { id: 22, name: 'A spectral shield hovers near you for the next minute, granting you a +2 bonus to AC and immunity to Magic Missile.' },
  { id: 23, name: 'A third eye appears in your forehead, giving you advantage on sight-based Wisdom (Perception) checks for 1 minute.' },
  { id: 24, name: 'A unicorn controlled by the DM appears in a space within 5 ft of you, then disappears 1 minute later.' },
  { id: 25, name: 'All allies within 20 ft of you gain a +2 bonus to attack and damage rolls on any melee weapon attack they make within the next minute.' },
  { id: 26, name: 'All allies within 20 ft of you gain a +2 bonus to attack and damage rolls on any ranged weapon attack they make within the next minute.' },
  { id: 27, name: 'All allies within 20 ft of you gain a -2 penalty to attack and damage rolls for any ranged attack they make within the next minute.' },
  { id: 28, name: 'All allies within 20 ft of you get gain a -2 penalty on attack and damage rolls for any melee attack they make in the next minute.' },
  { id: 29, name: 'All allies within 20 ft of you heal up to 3d8 hit points.' },
  { id: 30, name: 'All allies within 30 ft of you gain a -2 penalty to their AC for 1 minute.' },
  { id: 31, name: 'All creatures that can perceive you must make a Wisdom saving throw against your spell save DC or be frightened of you.' },
  { id: 32, name: 'All creatures within 20 ft of you are knocked prone.' },
  { id: 33, name: 'All creatures within 20 ft of you must make a Strength saving throw against your spell save DC or be knocked prone.' },
  { id: 34, name: 'All creatures within 20 ft of you, including you, must make a Dexterity save against your spell save DC or be affected by a faerie fire spell.' },
  { id: 35, name: 'All creatures within 30 ft of you must make a Wisdom saving throw. Any creature immune to magical sleep automatically succeeds on its saving throw. Those that fail fall asleep for 1d6 minutes.' },
  { id: 36, name: 'All creatures within 60 ft of you regain 2d8 hit points.' },
  { id: 37, name: 'All food and drink within 30 ft of you becomes putrid, spoiled, or rotten. Consuming this food deals 2d6 poison damage and causes the poisoned condition for 1 hour.' },
  { id: 38, name: 'All food and drink within 30 ft of you is purified.' },
  { id: 39, name: 'All gold you are carrying is now silver.' },
  { id: 40, name: 'All light sources within 60 ft radius extinguished' },
  { id: 41, name: 'All of your hair permanently falls out. Only a spell such as remove curse can end this effect.' },
  { id: 42, name: 'All silver you are carrying is now copper.' },
  { id: 43, name: 'All spells you cast within the next minute automatically fail.' },
  { id: 44, name: 'All unlocked doors/windows in 60 ft fly open' },
  { id: 45, name: 'All within 60 ft saves vs Wis 15 or drops w/e they hold' },
  { id: 46, name: 'All your allies within 20 ft of you gain a +2 bonus to their AC for 1 minute.' },
  { id: 47, name: 'All your clothing and equipment teleports to the nearest open space at least 15 ft from you that you can see.' },
  { id: 48, name: 'An eye appears on your forehead for the next minute. During that time, you have advantage on Wisdom (Perception) checks that rely on sight.' },
  { id: 49, name: 'An imp appears near you. Make a Charisma saving throw against your spell save DC. If you succeed, the imp is subservient, otherwise, it is hostile. The imp, if not banished or defeated, vanishes after 1 hour.' },
  { id: 50, name: 'An imp appears within 30 ft of you. Make a Charisma saving throw against your spell save DC. If you succeed it, the imp is subservient, otherwise, it is hostile. The imp, if not banished or defeated, vanishes after 1 day.' },
  { id: 51, name: 'Approximately 100 gallons of water appear over your head and those within 10 ft of you, evenly distributed above everybody within the radius.' },
  { id: 52, name: 'Cabbages sprout abundantly within a 30 ft radius' },
  { id: 53, name: 'Cast thunder wave centered on self' },
  { id: 54, name: 'Caster and target flung 10 ft in opposite directions' },
  { id: 55, name: 'Caster and target switch positions after spell' },
  { id: 56, name: 'Caster becomes frightened of a color for 1 hour' },
  { id: 57, name: 'Caster breathes 30 ft fire cone next time they speak' },
  { id: 58, name: 'Caster can mimic target fts voice perfectly for 24 hrs' },
  { id: 59, name: 'Caster can only breathe underwater for next minute' },
  { id: 60, name: 'Caster can only speak to animals for 24 hours' },
  { id: 61, name: 'Caster distracted by cloud of gnats for next minute' },
  { id: 62, name: 'Caster explodes with plant growth' },
  { id: 63, name: 'Caster falls Unconscious until start of next turn' },
  { id: 64, name: 'Caster fts arms become tentacles for 1 minute' },
  { id: 65, name: 'Caster fts face blackened by small explosion' },
  { id: 66, name: 'Caster fts fists become huge, deal 1d8 B dmg, 1 min' },
  { id: 67, name: 'Caster fts hands become covered in sticky goop' },
  { id: 68, name: 'Caster fts INT and STR swap for 1 hour' },
  { id: 69, name: 'Caster gains 100 lbs, move speed halved, 1 minute' },
  { id: 70, name: 'Caster gains 3 ft prehensile tail for 1 hour' },
  { id: 71, name: 'Caster grows antlers, sheds them in 24 hours' },
  { id: 72, name: 'Caster sees everyone as a decaying corpse for 24h' },
  { id: 73, name: 'Caster smells like lavender for 1d6 days' },
  { id: 74, name: 'Caster suffers a head cold for 24 hours' },
  { id: 75, name: 'Caster trapped in a giant glass ball' },
  { id: 76, name: 'Casters clothes become uncomfortably tight' },
  { id: 77, name: 'Choose 1 permanent or triggered effect that has happened to you or somebody else that you ftve received from this chart and remove it, even if it was beneficial.' },
  { id: 78, name: 'Creatures have disadvantage on saving throws against the next spell you cast in the next minute that involves a saving throw.' },
  { id: 79, name: 'Creatures within 30 ft are stuck in place vs Str DC 15' },
  { id: 80, name: 'During the next hour, you may re-roll any one save, attack roll, or skill check. If you do, you must take the new roll fts result.' },
  { id: 81, name: 'Each creature within 30 ft of you becomes invisible for the next minute. The invisibility ends on a creature when it attacks or casts a spell.' },
  { id: 82, name: 'Each creature within 30 ft of you takes 1d10 necrotic damage. You regain hit points equal to the sum of the necrotic damage dealt.' },
  { id: 83, name: 'Each creature within 30 ft of you takes 1d10 necrotic damage. You regain hit points equal to the sum of damage dealt.' },
  { id: 84, name: 'Each creature withn 30 ft of you takes 1d10 fire damage.' },
  { id: 85, name: 'Every creature within 15 ft of you takes 1 necrotic damage. If you are wounded, you regain hit points up to the amount of damage dealt. If you are not wounded, you gain this amount of temporary hit points.' },
  { id: 86, name: 'Every inanimate object that is not being worn or carried within 40 ft of you becomes enshrouded with shadows for 1 minute.Enshrouded objects are considered heavily obscured.' },
  { id: 87, name: 'Everything within 20 ft pulled 10 ft toward caster' },
  { id: 88, name: 'For 1 minute, a duplicate of yourself appears in the nearest open space which can take actions independently, and goes on the same Initiative as you. However, any damage it takes as well as any spell slots or sorcery point it uses applies to you as well.' },
  { id: 89, name: 'For 1 minute, any flammable item you touch, that you are not already wearing or carrying, bursts into flame.' },
  { id: 90, name: 'For 1 minute, one creature of your choice within 30 ft of you gains a -1 penalty to attack rolls, damage rolls, and their AC.' },
  { id: 91, name: 'For 1 minute, you gain resistance to nonmagical bludgeoning, piercing, and slashing damage.' },
  { id: 92, name: 'For 1d4 rounds your eyes go milk white and you are blind.' },
  { id: 93, name: 'For 2d6 days, you glow bright yellow. You have disadvantage on Stealth checks and anyone trying to perceive you has advantage on their Perception check.' },
  { id: 94, name: 'For 2d6 hours, you have a faint pink glow. Anyone trying to perceive you has advantage on their Perception check.' },
  { id: 95, name: 'For any spell that requires a saving throw you cast within the next minute, the target gains advantage.' },
  { id: 96, name: 'For one minute, any spell with a casting time of 1 action can be cast as a bonus action.' },
  { id: 97, name: 'For the next day, any time you make an ability check, roll 1d6 and add the result.' },
  { id: 98, name: 'For the next day, any time you make an ability check, roll 1d6 and subtract the result.' },
  { id: 99, name: 'For the next day, each time you say a word with the "s" sound, it sounds like a hissing snake.' },
  { id: 100, name: 'For the next day, everything you say must rhyme. If it doesn ftt, you take 1d6 psychic damage.' },
  { id: 101, name: 'For the next day, you are in the Border Ethereal near the location you were last in.' },
  { id: 102, name: 'For the next day, you gain proficiency in all skills that you are not already proficient in.' },
  { id: 103, name: 'For the next day, you have advantage on the next 2d6 rolls you make where you do not already have advantage.' },
  { id: 104, name: 'For the next day, your skin tone changes color every 30 minutes, cycling through the colors of the rainbow.' },
  { id: 105, name: 'For the next hour, any metal you touch is affected as if by the heat metal spell.' },
  { id: 106, name: 'For the next hour, any time you make an ability check, roll 1d4 and add the result.' },
  { id: 107, name: 'For the next hour, any time you make an ability check, roll 1d4 and subtract the result.' },
  { id: 108, name: 'For the next hour, any time you make an ability check, roll 1d6 and subtract the result.' },
  { id: 109, name: 'For the next hour, you appear to others to be the opposite gender.' },
  { id: 110, name: 'For the next hour, you are unable to read as the letters all appeared jumbled.' },
  { id: 111, name: 'For the next hour, you gain advantage on Charisma checks when dealing with any creature wearing black, but disadvantage if they are wearing white. If they are wearing both, this does not apply.' },
  { id: 112, name: 'For the next hour, you gain advantage on Charisma checks when dealing with any creature wearing red, but disadvantage if they are wearing green. If they are wearing both, this does not apply.' },
  { id: 113, name: 'For the next hour, you leave illusory flaming footprints that last for one minute.' },
  { id: 114, name: 'For the next hour, you may cast hellish rebuke up to 2d6 times.' },
  { id: 115, name: 'For the next hour, your hair appears like fire, shedding light as if affected by the continual flame spell.' },
  { id: 116, name: 'For the next minute all your spells with a casting time of 1 action have a casting time of 1 bonus action.' },
  { id: 117, name: 'For the next minute the energy type of all your spells is fire.' },
  { id: 118, name: 'For the next minute you are immune to fire damage.' },
  { id: 119, name: 'For the next minute you can teleport up to 20 ft as a bonus action on each of your turns, leaving sulfurous smoke in your wake.' },
  { id: 120, name: 'For the next minute, all melee attacks you make with a non-magical weapon gain a +1 bonus to hit and to damage, and are considered magical for the purpose of overcoming resistances.' },
  { id: 121, name: 'For the next minute, all spells with a casting time of 1 action or 1 bonus action require 2 consecutive actions to cast.' },
  { id: 122, name: 'For the next minute, all your fire spells shed bright light.' },
  { id: 123, name: 'For the next minute, all your spells with a casting time of 1 action have a casting time of 1 bonus action.' },
  { id: 124, name: 'For the next minute, any creature you touch takes 2d6 lightning damage.' },
  { id: 125, name: 'For the next minute, any flammable object you touch that is not being worn or carried by another creature bursts into flame.' },
  { id: 126, name: 'For the next minute, every creature within 60 ft of you that hears you speak only hears insults as if you are casting vicious mockery at first level.' },
  { id: 127, name: 'For the next minute, fall fire produced by your spells is blue and deals max damage.' },
  { id: 128, name: 'For the next minute, flaming wings cling to your back. You are affected by the jump spell' },
  { id: 129, name: 'For the next minute, light and darkness quickly alternate around you in a 30 ft radius, creating a strobe effect. Sight-based creatures gain a -1 penalty on attack rolls against you and Perception checks against you, and you gain a +1 bonus to Stealth checks.' },
  { id: 130, name: 'For the next minute, one creature of your choice gets a -2 penalty to its AC, attack rolls, and damage rolls.' },
  { id: 131, name: 'For the next minute, the range of all your fire spells are doubled.' },
  { id: 132, name: 'For the next minute, you are in the Border Ethereal near the location you were last in.' },
  { id: 133, name: 'For the next minute, you are unable to cast any spell that causes damage of any type.' },
  { id: 134, name: 'For the next minute, you can pass through any solid, non-magical wall that is 6 or fewer inches thick.' },
  { id: 135, name: 'For the next minute, you can see any invisible creature if you have line of sight to it.' },
  { id: 136, name: 'For the next minute, you can teleport up to 20 ft as a bonus action on each of your turns.' },
  { id: 137, name: 'For the next minute, you can teleport up to 20 ft as part of your movement on each of your turns.' },
  { id: 138, name: 'For the next minute, you cannot speak, but can breath fire as a bonus action. Treat this as a Dragonborn breath attack.' },
  { id: 139, name: 'For the next minute, you gain resistance to fire and cold damage.' },
  { id: 140, name: 'For the next minute, you gain resistance to necrotic and radiant damage.' },
  { id: 141, name: 'For the next minute, you gain resistance to poison and psychic damage.' },
  { id: 142, name: 'For the next minute, you gain resistance to thunder and force damage.' },
  { id: 143, name: 'For the next minute, you have double vision. This gives you disadvantage on ranged attacks (including spell attacks) and Perception checks involving sight.' },
  { id: 144, name: 'For the next minute, you have advantage on the next roll you make where you do not already have advantage.' },
  { id: 145, name: 'For the next minute, you must shout when you speak.' },
  { id: 146, name: 'For the next minute, you regain 5 hit points at the start of each of your turns.' },
  { id: 147, name: 'For the next minute, your hands are bathed in continual flame.  You may cast firebolt as a bonus action.' },
  { id: 148, name: 'For the next spell you cast within 1 minute that does damage, the damage is minimized.' },
  { id: 149, name: 'Gain the antipathy effects of the antipathy/sympathy spell for 3d6 days.' },
  { id: 150, name: 'Gain the effects of Eagle\'s Splendor as if by the enhance ability spell.' },
  { id: 151, name: 'Gain the sympathy effects of the antipathy/sympathy spell for 3d6 days.' },
  { id: 152, name: 'Geyser lifts caster 50 ft in air until start of next turn' },
  { id: 153, name: 'Gnats buzz around your head for 1 minute, distracting you. You must make a Constitution saving throw against your own spell save DC to cast any spell.' },
  { id: 154, name: 'Grass instantly sprouts to 3 ft tall within 20 ft, 1 minute' },
  { id: 155, name: 'Gravity reverses in 30 ft radius till start of next turn' },
  { id: 156, name: 'If spell would kill target, target fts extremities fly apart' },
  { id: 157, name: 'If target dies in next minute, its ghost haunts caster' },
  { id: 158, name: 'If you cast a spell with a saving throw within the next minute, the target gainsdisadvantage on its saving throw.' },
  { id: 159, name: 'If you die within the next hour, you immediately turn to ash and are reincarnated as if by a phoenix\'s rejuvenate.' },
  { id: 160, name: 'If you die within the next minute, you come back to life as if by the reincarnate spell.' },
  { id: 161, name: 'If you die within the next minute, you immediately come back to life as if by the Reincarnate spell.' },
  { id: 162, name: 'If you fall within the next day, you automatically have the benefit of the feather fall spell.' },
  { id: 163, name: 'Illusory butterflies and flower petals flutter in the air around you in a 10 ft radius for 1 minute.' },
  { id: 164, name: 'Illusory butterflies and flower petals flutter in the air within 10 ft of you for the next minute.' },
  { id: 165, name: 'Large floating eye follows caster for 1 hour' },
  { id: 166, name: 'Loud voice ridicules caster on init count 20 for 1 min' },
  { id: 167, name: 'Make a Constitution saving throw against your spell save DC. If you fail, you are stunned for 1 minute.' },
  { id: 168, name: 'Make a Wisdom saving throw against your own spell save DC. If you fail, you are polymorphed into giant dragonfly for 1 minute.' },
  { id: 169, name: 'Make a Wisdom saving throw against your own spell save DC. If you fail, you are transformed into a raven for 1 minute, as if by a polymorph spell.' },
  { id: 170, name: 'Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a cat for 1 minute, as if by a {5e|Polymorph } } spell.' },
  { id: 171, name: 'Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a giant rabbit for 1 minute, as if by the polymorph' },
  { id: 172, name: 'Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a giant spider for 1 minute, as if by the polymorph spell.' },
  { id: 173, name: 'Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a sheep for 1 minute, as if by the polymorph spell.' },
  { id: 174, name: 'Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a wolf for 1 minute, as if by a polymorph spell.' },
  { id: 175, name: 'Maximize the damage of the next damaging spell you cast within the next minute.' },
  { id: 176, name: 'Maximize the damage of the next fire spell you cast within a minute.  It ignores fire resistence.' },
  { id: 177, name: 'Mushrooms sprout around you in a 5 ft radius and vanish after 1 minute. If one is harvested and eaten within this time, the creature must make a Constitution saving throw against your spell save DC. On a failed save, it takes 5d6 poison damage. On successful one, it gains 5d6 temporary hit points.' },
  { id: 178, name: 'Next phrase spoken by caster becomes true' },
  { id: 179, name: 'Next turn caster takes no action, vomits 1d100 SP' },
  { id: 180, name: 'One creature of your choice gains a +1 bonus to attack rolls, damage rolls, and its AC for 1 minute.' },
  { id: 181, name: 'One creature of your choice gets a +2 bonus to all attack rolls, damage rolls, and their armor class AC for 1 minute.' },
  { id: 182, name: 'One of target fts eyes replaced by 500 GP sapphire' },
  { id: 183, name: 'One random gem worth 100gp appears near you.' },
  { id: 184, name: 'One randomly-chosen non-magical item in your possession that weighs 1 pound or less is duplicated.' },
  { id: 185, name: 'One randomly-chosen non-magical item in your possession that weighs 1 pound or less vanishes and is forever gone.' },
  { id: 186, name: 'Over the next minute, all plants within 20 ft of you grow as if affected by the plant growth spell when cast as an action.' },
  { id: 187, name: 'Permanently increase one ability score of your choice by 1 point. Permanently decrease a different ability score of your choice by 1 point. A spell such as remove curse can end this effect.' },
  { id: 188, name: 'Plants grow around you and you are restrained for 1 minute.' },
  { id: 189, name: 'Roll a d10. Your age changes by a number of years equal to the roll. If the roll is odd, you get younger (minimum 1 year old). If the roll is even, you get older.' },
  { id: 190, name: 'Roll a d10. Your height changes by a number of inches equal to the roll. If the roll is odd, you shrink. If the roll is even, you grow.' },
  { id: 191, name: 'Select one item you are carrying. It is permanently immune to fire damage.' },
  { id: 192, name: 'Small birds flutter and chirp in your vicinity for 1 minute, during which time you automatically fail any Stealth check.' },
  { id: 193, name: 'Smoke fumes from caster fts ears for 1 minute' },
  { id: 194, name: 'Spell ricochets off target to random creature in 30 ft' },
  { id: 195, name: 'Summon eight swarms of CR 1/4 rats.' },
  { id: 196, name: 'Swarm of rats carry caster 30 ft in random direction' },
  { id: 197, name: 'Target is cocooned in crystal until someone breaks it' },
  { id: 198, name: 'Target is transported to Ethereal Plane for 1 minute' },
  { id: 199, name: 'The next single target spell you cast within the next minute must target one additional target.' },
  { id: 200, name: 'The next spell you cast within the hour uses a slot level one level higher than what it normally requires.' },
  { id: 201, name: 'The next spell you cast within the next hour uses a spell slot of one level lower than what it normally requires. If the spell is a spell of 1st level, you still must expend a spell slot to cast it.' },
  { id: 202, name: 'The next spell you cast within the next minute that does damage, the damage is maximized.' },
  { id: 203, name: 'The next time you fall below 0 hit points within the next month, you automatically fail your first death saving throw.' },
  { id: 204, name: 'The power of your magic is strong! For the next hour, any spell you cast does not require a somatic component.' },
  { id: 205, name: 'The power of your magic is strong! For the next hour, any spell you cast does not require a verbal component.' },
  { id: 206, name: 'Up to three creatures you choose within 30 ft of you take 4d10 lightning damage.' },
  { id: 207, name: 'Weapons in 60 ft radius turn to food for 1 minute' },
  { id: 208, name: 'Within the next hour, you have advantage on the next roll you make where you do not already have advantage.' },
  { id: 209, name: 'You add your proficiency bonus to all Charisma checks for the next hour, if you do not already add it.' },
  { id: 210, name: 'You age 1d4 years and regain all spell slots' },
  { id: 211, name: 'You and all creatures within 30 ft of you gain vulnerability to acid damage for 1 minute.' },
  { id: 212, name: 'You and all creatures within 30 ft of you gain vulnerability to bludgeoning damage for 1 minute.' },
  { id: 213, name: 'You and all creatures within 30 ft of you gain vulnerability to cold damage for 1 minute.' },
  { id: 214, name: 'You and all creatures within 30 ft of you gain vulnerability to fire damage for 1 minute.' },
  { id: 215, name: 'You and all creatures within 30 ft of you gain vulnerability to force damage for 1 minute.' },
  { id: 216, name: 'You and all creatures within 30 ft of you gain vulnerability to lightning damage for 1 minute.' },
  { id: 217, name: 'You and all creatures within 30 ft of you gain vulnerability to necrotic damage for 1 minute.' },
  { id: 218, name: 'You and all creatures within 30 ft of you gain vulnerability to piercing damage for 1 minute.' },
  { id: 219, name: 'You and all creatures within 30 ft of you gain vulnerability to piercing damage for the next minute.' },
  { id: 220, name: 'You and all creatures within 30 ft of you gain vulnerability to poison damage for 1 minute.' },
  { id: 221, name: 'You and all creatures within 30 ft of you gain vulnerability to psychic damage for 1 minute.' },
  { id: 222, name: 'You and all creatures within 30 ft of you gain vulnerability to radiant damage for 1 minute.' },
  { id: 223, name: 'You and all creatures within 30 ft of you gain vulnerability to slashing damage for 1 minute.' },
  { id: 224, name: 'You and all creatures within 30 ft of you gain vulnerability to thunder damage for 1 minute.' },
  { id: 225, name: 'You are affected by a faerie fire spell for 1 minute. You automatically fail the saving throw.' },
  { id: 226, name: 'You are at the center of a 10 ft radius antimagic field that negates all magic equal to or less than your level for 1 hour and does not require concentration.' },
  { id: 227, name: 'You are at the center of a darkness spell for 1 minute.' },
  { id: 228, name: 'You are at the center of a fog spell which lasts for 1 minute.' },
  { id: 229, name: 'You are confused for 1 minute, as though you were affected by the confusion spell.' },
  { id: 230, name: 'You are frightened by the nearest creature until the end of your next turn.' },
  { id: 231, name: 'You are immune to being intoxicated by alcohol for the next 5d6 days.' },
  { id: 232, name: 'You are immune to disease for 1 week.' },
  { id: 233, name: 'You are immune to intoxication for the next 5d6 days.' },
  { id: 234, name: 'You are protected from Aberrations for 1 day. Such creatures cannot attack you or harm you unless they save a Charisma saving throw against your spell save DC.' },
  { id: 235, name: 'You are protected from Aberrations for 1 hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma savinng throw against your spell save DC.' },
  { id: 236, name: 'You are protected from Beasts for 1 day. Such creatures cannot attack you or harm you unless they save a Charisma saving throw against your spell save DC.' },
  { id: 237, name: 'You are protected from Beasts for 1 hour. Such creatures cannot attack you or harm you unless they succeed a Charisma saving throw against your spell save DC.' },
  { id: 238, name: 'You are protected from Celestials for 1 day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.' },
  { id: 239, name: 'You are protected from Celestials for 1 hour. Such creatures cannot attack you or harm you unless they succeed a on a Charisma saving throw against your spell save DC.' },
  { id: 240, name: 'You are protected from Elementals for 1 hour. Such reatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.' },
  { id: 241, name: 'You are protected from Elementals for one day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.' },
  { id: 242, name: 'You are protected from Fey for 1 day. Such ceatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.' },
  { id: 243, name: 'You are protected from Fey for one hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.' },
  { id: 244, name: 'You are protected from Fiends for one day. Such reatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.' },
  { id: 245, name: 'You are protected from Fiends for one hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma save against your spell save DC.' },
  { id: 246, name: 'You are protected from Plants for 1 day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.' },
  { id: 247, name: 'You are protected from Plants for 1 hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.' },
  { id: 248, name: 'You are protected from Undead for 1 day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.' },
  { id: 249, name: 'You are protected from Undead for one hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.' },
  { id: 250, name: 'You are resistant to all damage types for 1 minute.' },
  { id: 251, name: 'You are surrounded by a faint, offensive odor for 1 minute. You gain disadvantage on all Charisma checks.' },
  { id: 252, name: 'You are surrounded by a faint, pleasant odor. You gain advantage on all Charisma checks you make within the next minute.' },
  { id: 253, name: 'You are surrounded by a horrible, noxious odor for 1 minute. Anyone within 10 ft of you must make a Constitution saving throw or be stunned.' },
  { id: 254, name: 'You are surrounded by faint, ethereal music for 1 minute.' },
  { id: 255, name: 'You are surrounded by faint, ethereal music for the next minute.' },
  { id: 256, name: 'You are the center of a silence spell for 1 minute.' },
  { id: 257, name: 'You are transported to the Astral Plane until the end of your next turn, after which time you return to the space you previously occupied or the nearest unoccupied space if that space is occupied.' },
  { id: 258, name: 'You are vulnerable to Aberrations for 1 hour. Such creatures gain advantage when attacking you.' },
  { id: 259, name: 'You are vulnerable to Beasts for 1 hour. Such creatures gain advantage when attacking you.' },
  { id: 260, name: 'You are vulnerable to Celestials for 1 hour. Such creatures gain advantage when attacking you.' },
  { id: 261, name: 'You are vulnerable to Elementals for 1 hour. Such creatures gain advantage when attacking you.' },
  { id: 262, name: 'You are vulnerable to Fey for 1 hour. Such creatures gain advantage when attacking you.' },
  { id: 263, name: 'You are vulnerable to fiends for 1 hour. Such creatures gain advantage on attack rolls made against you.' },
  { id: 264, name: 'You are vulnerable to Plants for 1 hour. Such creatures gain advantage when attacking you.' },
  { id: 265, name: 'You are vulnerable to Undead for 1 hour. Such creatures gain advantage when attacking you.' },
  { id: 266, name: 'You are frightened by the nearest creature until the end of your next turn.' },
  { id: 267, name: 'You are invisible for 1 minute.' },
  { id: 268, name: 'You become frightened for 1d4 rounds.' },
  { id: 269, name: 'You become intoxicated for 2d6 hours.' },
  { id: 270, name: 'You become invisible and silent for 1 minute.' },
  { id: 271, name: 'You become invisible for the next minute. During that time, other creatures cannot hear you.The invisibility ends if you attack or cast a spell.' },
  { id: 272, name: 'You can detect the thoughts of 1 creature you can see within 30 ft of you for 1 minute.' },
  { id: 273, name: 'You can hear exceptionally well for 1 minute, gaining advantage for all Perception checks related to sound.' },
  { id: 274, name: 'You can smell exceptionally well for 1 minute, gaining blindsight with a radius of 10 ft and advantage on all Perception checks related to odor.' },
  { id: 275, name: 'You can take one additional action immediately.' },
  { id: 276, name: 'You cannot speak for 1 minute.When you try, pink bubbles float out of your mouth.' },
  { id: 277, name: 'You cannot speak for the next 1d4 rounds.Whenever you try, smoke comes out of your mouth and you cough.' },
  { id: 278, name: 'You cannot speak for the next minute.Whenever you try, pink bubbles float out of your mouth.' },
  { id: 279, name: 'You case a copy of your last cast fire spell.' },
  { id: 280, name: 'You cast burning hands on yourself and regain 1d4 sorcery points.' },
  { id: 281, name: 'You cast burning hands.' },
  { id: 282, name: 'You cast detect thoughts. This lasts for one hour and you do not need to concentrate to maintain the effect.  Each time you focus on a target you take 1d4 psychic damage.' },
  { id: 283, name: 'You cast fireball as a 3rd level spell centered on yourself, as if effected by the Careful Spell metamagic.' },
  { id: 284, name: 'You cast fog cloud centered on yourself.  The thick smog smells of brimstone.' },
  { id: 285, name: 'You cast grasping vine but it is a tentacle instead of a vine.' },
  { id: 286, name: 'You cast immolation.' },
  { id: 287, name: 'You cast polymorth on yourself.  If you fail the saving throw, turn into a fire elemental for the duration of the spell.' },
  { id: 288, name: 'You cast scorching ray at its lowest level.' },
  { id: 289, name: 'You cast Confusion centered on yourself.' },
  { id: 290, name: 'You cast Fireball as a 3rd-level spell centered on yourself.' },
  { id: 291, name: 'You cast Fly on a random creature within 60 ft of you.' },
  { id: 292, name: 'You cast Fog Cloud centered on yourself.' },
  { id: 293, name: 'You cast Grease centered on yourself.' },
  { id: 294, name: 'You cast Levitate on yourself.' },
  { id: 295, name: 'You cast Magic Missile as a 5th-level spell.' },
  { id: 296, name: 'You cast mirror image on yourself, which lasts for 1 minute and does not require concentration.' },
  { id: 297, name: 'You cast Mirror Image.' },
  { id: 298, name: 'You cast Polymorph on yourself. If you fail the saving throw, you turn into a sheep for the duration of the spell.' },
  { id: 299, name: 'You emanate light in a 30 ft radius for 1 minute. Any creature within 5 ft of you that can see is blinded until the end of its next.' },
  { id: 300, name: 'You emit a cloud of ash. Cast blur on yourself.' },
  { id: 301, name: 'You fall victim to a horrible cramp in both legs, reducing your speed by 10 ft for 1 hour.' },
  { id: 302, name: 'You feel a surge of warmth and regain 1d10 hit points.' },
  { id: 303, name: 'You feel extremely nauseated. Make a Constitution saving throw against your spell save DC. If you fail, you must spend your next action throwing up.' },
  { id: 304, name: 'You feel the incredible urge to relieve yourself. Until you do, your Strength and Intelligence are reduced by 1. If you do not relieve yourself in the next 2 minutes, the above effects are removed, but your Charisma score is reduced by 4 for 1 hour or until you change your trousers.' },
  { id: 305, name: 'You ftre feeling lucky. For the next hour, any time you make an ability check, roll 1d6 and add the result.' },
  { id: 306, name: 'You gain 1d6x10 pounds. You gradually return to your original weight over the course of 1 day.' },
  { id: 307, name: 'You gain a +1 to your AC for one minute.' },
  { id: 308, name: 'You gain a +2 bonus to your AC for 1 minute.' },
  { id: 309, name: 'You gain a -2 penalty to your AC for 1 minute.' },
  { id: 310, name: 'You gain an additional spell slot of your highest level for 1 week.' },
  { id: 311, name: 'You gain proficiency in all Constitution checks for the next hour, if you don ftt already have it.' },
  { id: 312, name: 'You gain proficiency in all Dexterity checks for the next hour, if you don ftt already have it.' },
  { id: 313, name: 'You gain proficiency in one skill of your choice that you are not already proficient in for one hour.' },
  { id: 314, name: 'You gain proficiency in one tool or weapon type you don ftt already have for 1 day.' },
  { id: 315, name: 'You gain proficiency in Wisdom checks for the next hour, if you don ftt already have it.' },
  { id: 316, name: 'You gain proficiency on all Intelligence checks for the next hour, if you don ftt already have it.' },
  { id: 317, name: 'You gain proficiency on all Strength checks for the next hour, if you don ftt already have it.' },
  { id: 318, name: 'You gain resistance to all damage for the next minute.' },
  { id: 319, name: 'You gain the ability to breath water for 1 day.' },
  { id: 320, name: 'You gain the ability to consume coal as if it were the fruit of the goodberry spell.' },
  { id: 321, name: 'You gain the ability to speak one additional language of your choice for 1 hour.' },
  { id: 322, name: 'You gain the ability to speak one language of your choice for 1 day.' },
  { id: 323, name: 'You gain the ability to speak one new language of your choice. However, you lose the ability to speak one language you already know.' },
  { id: 324, name: 'You gain the ability to speak with animals for 1 day.' },
  { id: 325, name: 'You gain the ability to speak with animals for one hour.' },
  { id: 326, name: 'You gain the ability to walk on water for 1 day.' },
  { id: 327, name: 'You gain the effects of the blur spell for 1 minute, which does not require concentration to maintain.' },
  { id: 328, name: 'You gain the service of a 2nd-level spiritual weapon for 1 minute.' },
  { id: 329, name: 'You gain the service of a phantom steed for 1 day.' },
  { id: 330, name: 'You gain the service of a phantom steed for 1 week.' },
  { id: 331, name: 'You gain the service of an arcane eye for 1 hour that does not require concentration.' },
  { id: 332, name: 'You gain the service of an arcane eye for 1 minute that does not require concentration.' },
  { id: 333, name: 'You gain the service of an arcane sword that does not require concentration until your next short or long rest.' },
  { id: 334, name: 'You gain the use of an unseen servant for 1 hour.' },
  { id: 335, name: 'You gain two spell slots at your second-highest level for 1 week.' },
  { id: 336, name: 'You gain blindsight with a radius of 60 ft for 1 minute.' },
  { id: 337, name: 'You gain darkvision with a radius of 60 ft for 1 minute. If you already have darkvision, you lose it for 1 minute.' },
  { id: 338, name: 'You gain freedom of movement for 1 day.' },
  { id: 339, name: 'You gain freedom of movement for 1 minute.' },
  { id: 340, name: 'You gain spider climb for 1 minute, and it does not require concentration to maintain.' },
  { id: 341, name: 'You gain tremorsense with a range of 30 ft for 1 minute.' },
  { id: 342, name: 'You get gain a -1 penalty to your AC for 1 minute.' },
  { id: 343, name: 'You glow with bright light in a 30 ft radius for the next minute. Any creature that ends its turn within 5 ft of you is blinded until the end of its next turn.' },
  { id: 344, name: 'You grow 1d6 inches in height. You gradually return to your original height over the course of 1 day.' },
  { id: 345, name: 'You grow a beard made of feathers, which remains until you sneeze.' },
  { id: 346, name: 'You grow a long beard made of feathers that remains until you sneeze, at which point the feathers explode out from your face.' },
  { id: 347, name: 'You have a momentary vision of your own death. If you fail a Wisdom saving roll at your spell DC, you are frightened for 1 minute.' },
  { id: 348, name: 'You have are surrounded by a spectral shield for 1 minute, giving you a +2 bonus to your AC and immunity to magic missile.' },
  { id: 349, name: 'You have the irresistible urge to scratch an itch in the middle your back, just out of reach, for 1 minute. If you do not scratch it using a back scratcher or some similar device, you must succeed a Constitution saving throw against your spell save DC to cast a spell.' },
  { id: 350, name: 'You hear a ringing in your ears for 1 minute. During this time, casting a spell that requires a verbal component requires a Constitution check against your spell save DC.' },
  { id: 351, name: 'You immediately drop to 0 hit points.' },
  { id: 352, name: 'You immediately gain 10 temporary hit points.' },
  { id: 353, name: 'You immediately gain 15 temporary hit points.' },
  { id: 354, name: 'You immediately gain 20 temporary hit points.' },
  { id: 355, name: 'You immediately heal 2d10 hit points.' },
  { id: 356, name: 'You immediately lose all unspent sorcery points and may not regain them until you have finished a long rest.' },
  { id: 357, name: 'You immediately lose one unspent sorcery point.' },
  { id: 358, name: 'You immediately take 1d10 radiant damage.' },
  { id: 359, name: 'You immediately take 2d10 psychic damage.' },
  { id: 360, name: 'You immediately take 2d4 psychic damage.' },
  { id: 361, name: 'You immediately take 2d6 psychic damage.' },
  { id: 362, name: 'You jump forward in time exactly 1 minute, for 1 minute. From the perspective of everyone else, you cease to exist during that time.' },
  { id: 363, name: 'You levitate 6 inches off the ground for 1 minute.' },
  { id: 364, name: 'You lose 1d6x5 pounds. You gradually return to your original weight over the course of 1 day.' },
  { id: 365, name: 'You lose proficiency in all skill rolls for 1d4 hours.' },
  { id: 366, name: 'You lose proficiency in one randomly chosen skill, tool, or weapon type for 2d6 days.' },
  { id: 367, name: 'You lose proficiency on all skill checks for 1 minute.' },
  { id: 368, name: 'You lose the ability to hear for 1 day.' },
  { id: 369, name: 'You lose the ability to see for 1 day. During this time, you have the blinded condition.' },
  { id: 370, name: 'You lose the ability to smell for 1 day.' },
  { id: 371, name: 'You lose the ability to smell for 1 hour.' },
  { id: 372, name: 'You make no sounds for 1 minute and you gain advantage on any Dexterity (Stealth) checks.' },
  { id: 373, name: 'You may immediately take 1 additional action.' },
  { id: 374, name: 'You no longer age, require food, drink, or air.' },
  { id: 375, name: 'You permanently forget one cantrip. A spell such as remove curse can restore your memory.' },
  { id: 376, name: 'You permanently gain one 1st-level spell slot but forget one cantrip that you already know. A spell such as remove curse can end this effect.' },
  { id: 377, name: 'You permanently gain one cantrip. A spell such as remove curse can end this effect.' },
  { id: 378, name: 'You permanently gain one spell slot of one level below your highest-level spell slot, but lose one 1st-level spell slot. A spell such as remove curse can end this effect.' },
  { id: 379, name: 'You permanently lose the ability to smell. This sense can be restored with a spell that removes curses such as remove curse.' },
  { id: 380, name: 'You recover 1 expended spell slot of your choice.' },
  { id: 381, name: 'You recover all your expended spell slots.' },
  { id: 382, name: 'You recover your lowest-level expended spell slot.' },
  { id: 383, name: 'You regain 2d10 hit points.' },
  { id: 384, name: 'You regain 2d4 sorcery points.' },
  { id: 385, name: 'You regain 5 hit points per round for 1 minute.' },
  { id: 386, name: 'You regain all expended sorcery points.' },
  { id: 387, name: 'You regain your lowest-level expended spell slot.' },
  { id: 388, name: 'You shrink 1d6 inches in height. You gradually return to your original height over the course of 1 day.' },
  { id: 389, name: 'You stand at the center a circular wall of fire with a radius of 15 ft. Any creature in any of the spaces covered by this fire must make a Dexterity saving throw against your spell DC or take 5d8 fire damage. The wall of fire remains for 1 minute.' },
  { id: 390, name: 'You stand at the center a circular wall of force with a radius of 15 ft. Any creature in any of the spaces covered by this wall must make a Dexterity saving throw against your spell DC or take 5d8 force damage. The wall remains for 1 minute.' },
  { id: 391, name: 'You summon 1d4 fire elementals CR 1/2' },
  { id: 392, name: 'You teleport to an alternate plane, then return to the location where you started after 1 minute.' },
  { id: 393, name: 'You teleport up to 60 ft to an unoccupied space of your choice that you can see.' },
  { id: 394, name: 'You teleport up to 60 ft to an unoccupied space that you can see.' },
  { id: 395, name: 'You transform into a large empty barrel for 1 minute, during which time you considered petrified.' },
  { id: 396, name: 'You transform into a marble statue of yourself for 1 minute, during which time you are considered petrified.' },
  { id: 397, name: 'You transform into a medium-sized potted plant for 1 minute, during which time you are considered petrified.' },
  { id: 398, name: 'You transform into a stone statue of yourself for 1 minute, during which time you are considered petrified.' },
  { id: 399, name: 'You transform into a stuffed toy resembling yourself for 1 minute, during which time you are considered petrified.' },
  { id: 400, name: 'You transform into an empty wooden chest for 1 minute, during which time you are considered petrified.' },
  { id: 401, name: 'You transform into an iron statue of yourself for 1 minute, during which time you are considered petrified.' },
  { id: 402, name: 'You turn into a potted plant until the start of your next turn. While a plant, you are incapacitated and have vulnerability to all damage. If you drop to 0 hit points, your pot breaks, and your form reverts.' },
  { id: 403, name: 'You turn to smoke and misty step.' },
  { id: 404, name: 'Your clothes become dirty and filthy. Until you can change and/or clean your clothes, your Charisma is reduced by 1.' },
  { id: 405, name: 'Your eyes glow red for 1 minute.' },
  { id: 406, name: 'Your eyes permanently change color. If they are a blue or grey shade, they turn dark brown, or vice versa. A spell such as remove curse can end this effect.' },
  { id: 407, name: 'Your eyes turn tawny or red and glow with a dim light.  A remove curse spell can end this effect.' },
  { id: 408, name: 'Your fingernails and toenails grow to an uncomfortable length. Until you trim them, your Dexterity is reduced by 1 and your speed is reduced by 5 ft, even if you ftre not wearing shoes.' },
  { id: 409, name: 'Your fingers become sore for 1 hour. During this time, you must succeed on a Dexterity saving throw against your spell save DC to cast a spell with a somatic component.' },
  { id: 410, name: 'Your ft sink into the ground, making you completely immobile for one minute. This has no effect if you were not standing on the ground when the spell was cast.' },
  { id: 411, name: 'Your hair falls out but grows back within 1 day.' },
  { id: 412, name: 'Your hair falls out but grows back within 24 hours.' },
  { id: 413, name: 'Your hair grows to double its current length over the next minute.' },
  { id: 414, name: 'Your haire turns bone white' },
  { id: 415, name: 'Your size increases by one size category for the next minute.' },
  { id: 416, name: 'Your skin dries and cracks, appearing charred and burnt with glowing magma-like cracks. A remove curse spell can end this effect.' },
  { id: 417, name: 'Your skin permanently darkens as if you have a tan, or if you are already dark-skinned, your skin becomes one shade lighter. A spell such as remove curse can end this effect.' },
  { id: 418, name: 'Your skin turns a vibrant shade of blue. A Remove Curse spell can end this effect.' },
  { id: 419, name: 'Your speed is increased by 10 ft for 1 day.' },
  { id: 420, name: 'Your speed is increased by 10 ft for 1 minute.' },
  { id: 421, name: 'Your spell components seem to have been rearranged. During the next hour, you must make an Intelligence check against your spell save DC to cast any spell that requires a material component.' },
  { id: 422, name: 'Your touch becomes painful to others, like the sting of nettles.' },
  { id: 423, name: 'Your Charisma is decreased by 2 for 1 hour.' },
  { id: 424, name: 'Your Charisma is increased by 2 for 1 day.' },
  { id: 425, name: 'Your Charisma is increased by 2 for 1 minute.' },
  { id: 426, name: 'Your Constitution is decreased by 2 for 1 hour.' },
  { id: 427, name: 'Your Constitution is increased by 2 for 1 day.' },
  { id: 428, name: 'Your Constitution is increased by 2 for 1 minute.' },
  { id: 429, name: 'Your Dexterity is decreased by 2 for 1 hour.' },
  { id: 430, name: 'Your Dexterity is increased by 2 for 1 day.' },
  { id: 431, name: 'Your Dexterity is increased by 2 for 1 minute.' },
  { id: 432, name: 'Your Intelligence is decreased by 2 for 1 day.' },
  { id: 433, name: 'Your Intelligence is increased by 2 for 1 day.' },
  { id: 434, name: 'Your Intelligence is increased by 2 for 1 minute.' },
  { id: 435, name: 'Your Strength is decreased by 2 for 1 hour.' },
  { id: 436, name: 'Your Strength is increased by 2 for 1 day.' },
  { id: 437, name: 'Your Strength is increased by 2 for 1 minute.' },
  { id: 438, name: 'Your Wisdom is decreased by 2 for 1 hour.' },
  { id: 439, name: 'Your Wisdom is increased by 2 for 1 day.' },
  { id: 440, name: 'Your Wisdom is increased by 2 for 1 minute.' }
];
